services:
  frontend:
    build:
      context: ./frontend
    container_name: Astrea-Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: Astrea-Backend
    ports:
      - "3000:3000"